### ISSUE TITLE
And now "Find in selection" is gone

### ISSUE THREAD

**Issue by bengalamx** [thierryc/Sketch-Find-And-Replace#107]
Even if I restart Sketch :(

<img width="680" alt="Captura de Pantalla 2020-02-02 a la(s) 12 28 10" src="https://user-images.githubusercontent.com/3253845/73613056-7acfec80-45b7-11ea-84d9-ee2a92eccb9b.png">

**Comment by rodionovd** [comment]
I believe this bug was never fixed even though this issue has been marked as completed. Here's a corresponding thread on Sketch Forum: https://forum.sketch.com/t/does-anyone-know-a-reliable-plugin-for-find-and-replace-text/2314

There's also [a workaround]( https://forum.sketch.com/t/does-anyone-know-a-reliable-plugin-for-find-and-replace-text/2314/16):

> I had to reset the settings for this plugin (click the ?, then scroll down). After I did this, the option for ‘selection’ was back and the plugin worked well as it did before.

**Comment by miguelpeniche** [comment]
I am using Figma since those days. :)
