### ISSUE TITLE
Doesn't work? Sketch Version 44.1 (41455)

### ISSUE THREAD

**Issue by micahdaigle** [thierryc/Sketch-Find-And-Replace#6]
I installed and it doesn't seem to work. I've run several Find & Replace queries but nada.

**Comment by sebastienbarre** [comment]
Same here

**Comment by beeccy** [comment]
I've installed this in my Sketch Version 44.1 (41455), and I get the menu under Plugins, though when I click Find and Replace nothing happens. Same when I click Shift + Commad + F. There is no pop-up and there doesn't seem to be anything happening. Have I done something wrong? I followed the instructions and it should work according to them.

**Comment by thierryc** [comment]
Fix for 45.

**Comment by beeccy** [comment]
Thank you very much for continuing the development here! 

I've tested this for my Sketch 45.1, but the window still doesn't appear. I have Find and Replace version 1.7. I've tested Shift + Command + F and clicking it under Plug-ins.

**Comment by thierryc** [comment]
Please, provide me more information:

- Your Sketch Version. 
- Installed plugins.

Try to disable some plugin also.

UnInstall the plugin and reinstall it:

Menu: Plugins -> Manage Plugins
Windows: [+] at the bottom -> reveal the plugin folder.

Remove the find and replace plugin.

Download the last stable version. 
https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.8
Double click on it.

**Comment by thierryc** [comment]
Unfortunately, I can't try the 44.1 version anymore.
All releases are archived into the release page. (From 1.2)

https://github.com/thierryc/Sketch-Find-And-Replace/releases/

**Comment by beeccy** [comment]
Thanks for your quick response!

Sketch version: 45.1 (43504)
MacOS Sierra version: 10.12.5

Active plugins: 
Invision Craft version: 1.7.56
Find and Replace version: I removed the previous plugin and downloaded https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/v1.2 and https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.8 without it working. 

I've also deactivated all the plugins in Sketch (except Invision Craft due to that many of my projects needs this) without the Find and Replace appearing. When I click it, I get a response that it's been clicked on it in Plugins, but that's just about it. I've uninstall and reinstalled over 5 times, yet there's no difference. 

Unfortunately I can't come with much since nothing happens and I don't receive an error message of any kind. 

The only thing that I can think of, is that Invision Craft might be the reason why Find and Replace doesn't work, though that's just a hypothesis. Apologetically, I can't test this since if I remove it, I might loose all of my prototyping parts of the projects and that's many, many hours of lost work that I can't afford to lose.

Thank you again for your quick response and wonderful initiative in this project!

**Comment by beeccy** [comment]
Strange. I found the log file, I hope it's helpful! Thank you very much!

P.S. I updated Sketch to 45.2 (43514) this morning, though no changes to the plugin. 

```ReferenceError: Can't find variable: initDefaults
line: 25
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
stack: initialise@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:25:36
FindAndReplace@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:11:15
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 25
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
stack: initialise@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:25:36
FindAndReplace@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:11:15
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 25
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
stack: initialise@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:25:36
FindAndReplace@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Find-And-Replace-1.8/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:11:15
 «Plugin Output»```

**Comment by thierryc** [comment]
Thank you Beeccy !

please try 1.9 version 
[Sketch Find And Replace 1.9](https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.9)

**Comment by thierryc** [comment]
Or 10 ... and let me know.

**Comment by beeccy** [comment]
I tested with https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.9 and https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.10-beta2, but for some reason it's still not working for me. It seems the logs haven't changed. Thank you again for helping me out! It's much appreciated!

```
ReferenceError: Can't find variable: initDefaults
line: 25
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
stack: initialise@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:25:36
FindAndReplace@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:11:15
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 25
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
stack: initialise@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:25:36
FindAndReplace@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:11:15
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 25
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
stack: initialise@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:25:36
FindAndReplace@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:11:15
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 25
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
stack: initialise@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:25:36
FindAndReplace@/Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript:11:15
 «Plugin Output»
```

**Comment by thierryc** [comment]
Try to go to your Sketch Plug-in folder. 

Menu: Plugins -> Manage Plugins
Windows: [+] at the bottom -> reveal the plugin folder.

Remove (trash) the plugin and install the 1.10 version released this morning.

**Comment by thierryc** [comment]
Line 25 (or 26) should be:

userDefaults = initDefaults("cx.ap.sketch-find-and-replace", presets);

not

userDefaults = initDefaults("com.martinsteven.sketch-find-and-replace", presets);

**Comment by beeccy** [comment]
I've uninstalled and deleted the previous version I had, and installed https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/1.10-beta2. When I ran the script, it still had `userDefaults = initDefaults("com.martinsteven.sketch-find-and-replace", presets);` in it. 

When I checked the script I downloaded, it had `userDefaults = initDefaults("cx.ap.sketch-find-and-replace", presets);`.

I added the line of code in `Run Script`, however it still didn't want to appear. I still get:
```
ReferenceError: Can't find variable: initDefaults
line: 26
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 26
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 26
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 26
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 26
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
 «Plugin Output»
ReferenceError: Can't find variable: initDefaults
line: 26
sourceURL: /Users/beeccy/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Find And Replace.sketchplugin/Contents/Sketch/FindAndReplace.sketchscript
column: 36
 «Plugin Output»
```

I'm beginning to wonder whether it's Sketch that is buggy, because it's really strange that all other plugins I have work perfectly well except Find-and-replace. I downloaded https://github.com/yo-op/sketchcachecleaner/releases to delete cache from Sketch, but this didn't solve anything either. It seems like Sketch is running the old script even if I try to make it use the new one. However, when I opened `Run Script` it claims it is running the new one, but in the console box it's still complaining about the `initDefaults`.

Thank you so much for looking into this. I understand it must be frustrating when the continuous `initDefaults` error appears no matter what. Maybe there's a place in Sketch I need to manually fix that line of code?

**Comment by thierryc** [comment]
Run script can't work like this! 
You need to add all dependences before. 
Try to add this at the top and remove the import statement. 
But the best way tu use the script is from the menu ! 

```
var kPluginDomain;

var initDefaults = function(pluginDomain, initialValues) {
	kPluginDomain = pluginDomain

	var defaults = [[NSUserDefaults standardUserDefaults] objectForKey:kPluginDomain]
	var defaultValues = {}
    var dVal;

    for (var key in defaults) {
    	defaultValues[key] = defaults[key]
	}

	for (var key in initialValues) {
		dVal = defaultValues[key]
		if (dVal == nil) defaultValues[key] = initialValues[key]
	}

	return defaultValues
}

var saveDefaults = function(newValues) {
	if (kPluginDomain) {
		var defaults = [NSUserDefaults standardUserDefaults]
		[defaults setObject: newValues forKey: kPluginDomain];
	}
}
```

**Comment by beeccy** [comment]
Oh my god! That actually worked!! I replaced `@import "plugindefaults.js"` with that code (the latest above) and saved it under Plugins in the Find And Replace.sketchplugin. When I run it now, it works! 

Thank you so very much! This is a lifesaver! Now I can be more effective creating sketches rather than correcting the same sentence on 15 different versions of it! This issue is resolved thanks to you! 👍 Best of luck on further development!

**Comment by thierryc** [comment]
Good News !
